dependency:
  name: galaxy
driver:
  name: docker
  port_bindings:
    '8080': 80
    '38888': 38888
    '44443': 443
platforms:
  - name: debian-11
    image: docker.io/geerlingguy/docker-debian11-ansible:latest
    privileged: true
    command: /sbin/init
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
provisioner:
  name: ansible
  log: true
scenario:
  name: debian-11
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
verifier:
  name: ansible
