---
- name: List databases (initial)
  ansible.builtin.uri:
    url: "{{ base_url }}/databases"
    method: GET
    status_code: 200
    validate_certs: no
  register: db_list_initial

- name: Create DB (check mode)
  ravendb.ravendb.database:
    url: "{{ base_url }}"
    database_name: "{{ db_check }}"
    replication_factor: 1
    state: present
  check_mode: yes
  register: db_check_create

- name: Assert would created DB msg (check mode)
  ansible.builtin.assert:
    that:
      - db_check_create.changed
      - "'would be created' in db_check_create.msg | lower"

- name: Verify DB not created on check mode
  ansible.builtin.uri:
    url: "{{ base_url }}/databases"
    method: GET
    validate_certs: no
  register: dbs_after_check_create

- name: Assert DB not created
  ansible.builtin.assert:
    that:
      - "db_check not in (dbs_after_check_create.json.Databases | map(attribute='Name') | list | default([]))"

- name: Create DB
  ravendb.ravendb.database:
    url: "{{ base_url }}"
    database_name: "{{ db_main }}"
    replication_factor: 1
    database_settings:
      Indexing.MapTimeoutAfterEtagReachedInMin: "20"
    state: present
  register: db_main_created

- name: Assert DB created
  ansible.builtin.assert:
    that:
      - db_main_created.changed
      - "'created successfully' in db_main_created.msg | lower"

- name: Verify DB created
  ansible.builtin.uri:
    url: "{{ base_url }}/databases"
    method: GET
    validate_certs: no
  register: dbs_after_create

- name: Assert DB present
  ansible.builtin.assert:
    that:
      - "db_main in (dbs_after_create.json.Databases | map(attribute='Name') | list)"

- name: Re-run create DB (idempotency)
  ravendb.ravendb.database:
    url: "{{ base_url }}"
    database_name: "{{ db_main }}"
    replication_factor: 1
    state: present
  register: db_main_again

- name: Assert DB creation idempotent
  ansible.builtin.assert:
    that:
      - "not db_main_again.changed"
      - "'already exists' in db_main_again.msg | lower"
      - "'no changes' in db_main_again.msg | lower"
