---
dependency:
  name: galaxy
driver:
  name: docker
  port_bindings:
    '8080': 80
    '38888': 38888

platforms:
  - name: ubuntu-bionic-node-a
    hostname: ubuntu-bionic-node-a
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    command: /usr/sbin/init
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    networks:
      - name: ravendbnet

  - name: ubuntu-bionic-node-b
    hostname: ubuntu-bionic-node-b
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    command: /usr/sbin/init
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    networks:
      - name: ravendbnet

  - name: ubuntu-bionic-node-c
    hostname: ubuntu-bionic-node-c
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    command: /usr/sbin/init
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    networks:
      - name: ravendbnet

provisioner:
  name: ansible
  log: true
scenario:
  name: rolling-update
  test_sequence:
    - destroy
    - create
    - converge
verifier:
  name: ansible
