##################################################################################################
# playbooks/setup_ravendb.yml
#
# Purpose: Install or upgrade RavenDB on target Linux hosts
#
# What it does:
#   - Installs OS prerequisites (apt/yum)
#   - Detects distro/arch and downloads RavenDB (Ubuntu: DEB; others: tarball)
#   - Creates ravendb user/group and required directories
#   - Renders non-secure settings.json from the selected preset (+ optional overrides)
#   - Installs license file if provided
#   - Installs/updates binaries, writes systemd unit, sets CAP_NET_BIND_SERVICE
#   - Starts/enables the ravendb systemd service
#
# Notes:
#   - Requires privilege escalation (become: true)
#   - Examples for choosing build (stable/nightly, latest/specific) are provided below
#   - This playbook covers non-secure setup only (no LE/self-signed here, see secure setup playbooks)
#   - Idempotent:
#       - Same version + same overrides => no change
#       - Same version + new/changed settings overrides => updates settings.json + restarts service
#       - Different version => upgrades/downgrades RavenDB + restarts service
#   - Key vars:
#       ravendb_state, ravendb_version, ravendb_version_minor, ravendb_release_channel
#       ravendb_hostname, ravendb_license_file, ravendb_settings_preset, ravendb_settings_override
###################################################################################################


- name: Install/Upgrade RavenDB
  hosts: ravendb_nodes
  remote_user: root
  roles:
    - role: ravendb.ravendb.ravendb_node
      vars:
          ravendb_state: present
          ravendb_version_minor: 6.2
          ravendb_version: latest
          ravendb_release_channel: stable
          ravendb_hostname: "{{ ansible_host }}"
          ravendb_license_file: "/home/user/license.json" # path to license file on the controller node
          ravendb_settings_preset: default
          ravendb_settings_override: # optional server's settings overrides
            Logs.Mode: "Information"

# -----------------------------------------------------------------
# Build selection snippets (stable/nightly, latest/specific)
# -----------------------------------------------------------------

# Latest STABLE in minor (e.g., 7.1.x)
- name: Include ravendb_node (latest stable)
  ansible.builtin.include_role:
    name: ravendb.ravendb.ravendb_node
  vars:
    ravendb_state: present
    ravendb_version: latest
    ravendb_version_minor: 7.1
    ravendb_release_channel: stable

# Latest NIGHTLY in minor
- name: Include ravendb_node (latest nightly)
  ansible.builtin.include_role:
    name: ravendb.ravendb.ravendb_node
  vars:
    ravendb_state: present
    ravendb_version: latest
    ravendb_version_minor: 7.1
    ravendb_release_channel: nightly

# Specific STABLE
- name: Include ravendb_node (specific stable)
  ansible.builtin.include_role:
    name: ravendb.ravendb.ravendb_node
  vars:
    ravendb_state: present
    ravendb_version: 7.1.1
    ravendb_release_channel: stable

# Specific NIGHTLY
- name: Include ravendb_node (specific nightly)
  ansible.builtin.include_role:
    name: ravendb.ravendb.ravendb_node
  vars:
    ravendb_state: present
    ravendb_version: 7.1.3-nightly-20250905-1218
    ravendb_release_channel: nightly