---
- hosts: all
  remote_user: root
  roles:
    - role: ravendb.ravendb.ravendb_node
      vars:
          ravendb_state: present
          ravendb_version_minor: 6.2
          ravendb_settings_preset: default